import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {createState,advance,rebalance,tick,getArena,RULES} from '../src/legacy-spot.mjs';import {localDB} from '../src/local-db.mjs';
const start=1800000000;const candles=(n=40)=>Array.from({length:n},(_,i)=>{const p=100+(i%6)*.3;return [start-1200+i*60,p-.2,p+.2,p,p+.1,1];});
test('only complete candles, deterministic replay and no double execution',()=>{const s=createState('BTC-USDT',start);const result=advance(s,candles(),start+120);assert.equal(result.snapshots.length,2);assert.equal(s.lastT,start-60);const repeated=advance(result.state,candles(),start+120);assert.equal(repeated.trades.length,0);assert.equal(repeated.snapshots.length,0);assert.equal(result.state.lastT,start+60);assert.deepEqual(advance(s,candles(),start+120),result);});
test('cost conservation and nonnegative cash/quantity',()=>{const s=createState('BTC-USDT',start),b=s.bots[0];const t=rebalance(s,b,1,100,start,'test',start+60);assert(Math.abs(b.cash+b.qty*100-(10000-t.cost))<1e-7);const sell=rebalance(s,b,0,100,start+60,'test',start+120,true);assert.equal(b.qty,0);assert(Math.abs(b.cash-(10000-t.cost-sell.cost))<1e-7);assert(b.cash>=0);});
test('missing minute halts without inventing price',()=>{const s=createState('BTC-USDT',start),data=candles().filter(c=>c[0]!==start);const r=advance(s,data,start+600);assert.equal(r.snapshots.length,0);assert.equal(r.state.lastT,start-60);});
test('future bars do not affect past decisions',()=>{const s=createState('BTC-USDT',start),data=candles(),now=start+120;const changed=data.map(c=>c[0]>=now?[c[0],1000,2000,1500,1800,1]:c);assert.deepEqual(advance(s,data,now),advance(s,changed,now));});
test('drawdown triggers liquidation and no re-entry',()=>{const s=createState('BTC-USDT',start);s.bots[1].cash=0;s.bots[1].qty=100;s.bots[1].peak=20000;const r=advance(s,candles(),start+120);assert.equal(r.state.bots[1].dead,true);assert.equal(r.state.bots[1].qty,0);assert(r.trades.some(t=>t.reason.includes('淘汰')));});
test('season closes positions and benchmark at end',()=>{const s=createState('BTC-USDT',start);s.endsAt=start+120;const r=advance(s,candles(),start+600);assert.equal(r.state.finished,true);assert(r.state.bots.every(b=>b.qty===0));assert.equal(r.state.baselineQty,0);assert.equal(r.snapshots.length,2);});
test('delayed execution has auditable catchup tag',()=>{const r=advance(createState('BTC-USDT',start),candles(),start+6000);assert(r.trades.length>0);assert(r.trades.every(t=>t.catchup===1));});
test('SQLite persistence and concurrent CAS prevent duplicate trades',async()=>{const folder=fs.mkdtempSync(path.join(os.tmpdir(),'trimon-test-'));const filename=path.join(folder,'test.sqlite');let db=localDB(filename,path.resolve('drizzle'));await getArena(db,'BTC-USDT',start);const fetcher=async()=>new Response(JSON.stringify(candles().map(c=>[c[0]*1000,c[3],c[2],c[1],c[4],c[5]])));await Promise.all([tick(db,'BTC-USDT',start+300,fetcher),tick(db,'BTC-USDT',start+300,fetcher)]);const a=await getArena(db,'BTC-USDT',start+300);assert(a.totalTrades>0);const count=await db.prepare('SELECT COUNT(*) AS n FROM trades').first();assert.equal(count.n,a.totalTrades);db.close();db=localDB(filename,path.resolve('drizzle'));const b=await getArena(db,'BTC-USDT',start+300);assert.equal(a.lastT,b.lastT);assert.deepEqual(a.bots,b.bots);await tick(db,'BTC-USDT',start+300,fetcher);const after=await db.prepare('SELECT COUNT(*) AS n FROM trades').first();assert.equal(after.n,count.n);db.close();});


